version: '3.8'

services:
  frontend:
    build:
      context: ./volatriafront
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - volatria-network

  backend:
    build:
      context: ./volatriabak
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./volatriabak/volatria.db:/app/volatria.db
    environment:
      - API_KEY=your_alpha_vantage_api_key
    networks:
      - volatria-network

networks:
  volatria-network:
    driver: bridge 